# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaRegistro.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaRegistro(object):
    def setupUi(self, Ventana_Registro):
        Ventana_Registro.setObjectName("Ventana_Registro")
        Ventana_Registro.setFixedSize(302, 362)
        self.centralwidget = QtWidgets.QWidget(Ventana_Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 261, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.BotonRealizarRegistro = QtWidgets.QPushButton(self.frame)
        self.BotonRealizarRegistro.setGeometry(QtCore.QRect(70, 190, 131, 51))
        self.BotonRealizarRegistro.setObjectName("BotonRealizarRegistro")
        self.BotonVolver = QtWidgets.QPushButton(self.frame)
        self.BotonVolver.setGeometry(QtCore.QRect(90, 260, 91, 31))
        self.BotonVolver.setObjectName("BotonVolver")
        self.Password = QtWidgets.QLineEdit(self.frame)
        self.Password.setGeometry(QtCore.QRect(40, 120, 191, 41))
        self.Password.setObjectName("Password")
        self.User = QtWidgets.QLineEdit(self.frame)
        self.User.setGeometry(QtCore.QRect(40, 40, 191, 41))
        self.User.setObjectName("User")
        self.LabelPassword = QtWidgets.QLabel(self.frame)
        self.LabelPassword.setGeometry(QtCore.QRect(40, 90, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelPassword.setFont(font)
        self.LabelPassword.setObjectName("LabelPassword")
        self.LabelUser = QtWidgets.QLabel(self.frame)
        self.LabelUser.setGeometry(QtCore.QRect(40, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LabelUser.setFont(font)
        self.LabelUser.setObjectName("LabelUser")
        Ventana_Registro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ventana_Registro)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Registro)

    def retranslateUi(self, Ventana_Registro):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Registro.setWindowTitle(_translate("Ventana_Registro", "MainWindow"))
        self.BotonRealizarRegistro.setText(_translate("Ventana_Registro", "Regisitrar"))
        self.BotonVolver.setText(_translate("Ventana_Registro", "Volver"))
        self.LabelPassword.setText(_translate("Ventana_Registro", "Contraseña: "))
        self.LabelUser.setText(_translate("Ventana_Registro", "Nombre de usuario:"))
