# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaLogin(object):
    def setupUi(self, VentanaLogin):
        VentanaLogin.setObjectName("VentanaLogin")
        VentanaLogin.setEnabled(True)
        VentanaLogin.setFixedSize(400, 195)
        self.centralwidget = QtWidgets.QWidget(VentanaLogin)
        self.centralwidget.setMinimumSize(QtCore.QSize(40, 50))
        self.centralwidget.setObjectName("centralwidget")
        self.AreaDatos = QtWidgets.QFrame(self.centralwidget)
        self.AreaDatos.setGeometry(QtCore.QRect(0, 0, 411, 121))
        self.AreaDatos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AreaDatos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AreaDatos.setObjectName("AreaDatos")
        self.Imagen = QtWidgets.QFrame(self.AreaDatos)
        self.Imagen.setGeometry(QtCore.QRect(10, 20, 81, 81))
        self.Imagen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Imagen.setObjectName("Imagen")
        self.Password = QtWidgets.QLineEdit(self.AreaDatos)
        self.Password.setGeometry(QtCore.QRect(120, 70, 241, 31))
        self.Password.setObjectName("Password")
        self.User = QtWidgets.QLineEdit(self.AreaDatos)
        self.User.setGeometry(QtCore.QRect(120, 30, 241, 31))
        self.User.setObjectName("User")
        self.BotonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.BotonLogin.setGeometry(QtCore.QRect(290, 130, 91, 41))
        self.BotonLogin.setObjectName("BotonLogin")
        self.BotonRegistro = QtWidgets.QPushButton(self.centralwidget)
        self.BotonRegistro.setGeometry(QtCore.QRect(180, 130, 91, 41))
        self.BotonRegistro.setObjectName("BotonRegistro")
        VentanaLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaLogin)
        QtCore.QMetaObject.connectSlotsByName(VentanaLogin)

    def retranslateUi(self, VentanaLogin):
        _translate = QtCore.QCoreApplication.translate
        VentanaLogin.setWindowTitle(_translate("VentanaLogin", "MainWindow"))
        self.BotonLogin.setText(_translate("VentanaLogin", "Login"))
        self.BotonRegistro.setText(_translate("VentanaLogin", "Registrarse"))
